### ISSUE TITLE
Wrong files

### ISSUE THREAD

**Issue by Casterol** [InsaneFirebat/sm_practice_hack#6]
https://github.com/InsaneFirebat/sm_practice_hack/blob/Contamination/releases/Contamination_InfoHUD_Savestates_2.4.1.ips
https://github.com/InsaneFirebat/sm_practice_hack/blob/Retroid/releases/Retroid_InfoHUD_Savestates_2.2.7_beta3.ips
These 2 aren't real patches.

**Comment by InsaneFirebat** [comment]
Thank you for pointing this out. I typically don't use builds with savestates enabled, so I didn't notice that side of things had failed and generated empty patches. Both cases are fixed in the following commits.
https://github.com/InsaneFirebat/sm_practice_hack/commit/f2de2ca0ac9a4565c336b835d3393f9f3bf85d2e
https://github.com/InsaneFirebat/sm_practice_hack/commit/3230b54aeba3ec5988cc4941dfb9dc4b848b4d82
